from polygon import *

class Source:
    """ Class managing DEGAS2 sources.
    """
    def __init__(self,nflights,stype,species,rootspecies=None,specify_flux=True,sourcefile="sourcefile.txt",
                 sourcefile_fmt="tabular",pufftemp=None,strength=None,stratum=None,segment=None):
        """ Initialization of DEGAS Source class.
            Args:
                nflights: (int) Number of flights
                stype: (str) one of ["plate", "puff", "vol_source", "plt_e_bins", "snapshot", "recomb"]
                species: (str) species generated by the source, identifier must be in the list of test species for the problem.
            Kwargs:
                rootspecies: (str) species underlying the source.
                specify_flux: (bool) informs the code that 'source_strength' is a flux of particles.
                sourcefile: (str) filename for tabular input
                sourcefile_fmt: (str) one of ['tabular','row']
                pufftemp: (float) Temperature of the puff in Kelvin.
                strength: (list of float) strength of the source, units are determined by specify_flux.
                           The defineback program expects one source_strength for every stratum, segment.
                           The values are separated by spaces: S1 S2 S3...
                stratum: (list of int) Used with strength and segment to specify the location.
                                The values are separated by spaces: 3 3 3
                segmment: (list of int) Used with strength, stratum to specify the location of the source.
                                The values are separated by spaces: 100 200 300
        """
        self.nflights = nflights
        self.type = stype
        self.species = species
        #
        if not rootspecies:
            self.rootspecies = self.species
        else:
            self.rootspecies = rootspecies
        #
        if specify_flux:
            self.specify_units = "specify_flux"
        else:
            self.specify_units = "specify_current"
        #
        if pufftemp:
            self.pufftemp = pufftemp
        else:
            self.pufftemp=None
        # 
        if strength:
            self.sourcefile = None
            # The source is to be specified with a combination of 'strength', 'stratum', and 'segment'
            # However, if the given strength/segment/stratum lists are too long, this method will write a sourcefile.
            self.set_source_from_segments(strength, stratum, segment)
            self.check_segments()
        else:
            self.sourcefile = sourcefile
            
    def set_source_from_segments(self, strength, stratum, segment):
        """ Method to set Source attrs given: strength, stratum, segment.
        Args:
            strength: (str, float, or list-of-float)
                    The correct attr is created if strength=1e24, '1e24' or a list thereof
            stratum: (str, int, or list-of-int)
                    The correct attr is created if stratum=3, '3', or a list thereof.
            segment: (str, int, or list-of-int)
                    There are special strings which are interepreted by this method,
                    "*" = all segments wildcard, in this case strength and stratum should be one (str) value.
                    "100:200" = if a colon ":" is present, the ints on either side are interpreted as a range.
                                the strength and stratum args are made to be the same len as the resulting list.
                    "100 200" = this is the format expected by defineback, in this case 'segment' is temporarily
                                reverted to [int, int] format to assert the shape of strength and stratum.
        """
        # Sanitize inputs,
        if not isinstance(strength, list):
            strength = [strength]
        if not isinstance(stratum, list):
            stratum = [stratum]

        if isinstance(segment, str):
            if segment == "*":
                # wildcard case, other values should have len=1
                self.segment = segment
                self.strength = str(strength[0]) # can be float
                self.stratum = str(int(stratum[0])) # must be int.
                return
            elif ":" in segment:
                # start:end case,
                s1, s2 = [ int(s) for s in segment.split(":") ]
                segment = list(range(s1,s2))
                N = len(segment)
                if len(strength) != N:
                    # distribute strength over the number of segments.
                    strength = [float(strength[0])/N]*N
                if len(stratum) != N:
                    stratum = [stratum[0]]*N
                # add as attrs,
                self.segment = " ".join([f"{int(s)}" for s in segment])
                self.strength = " ".join([f"{s:.3e}" for s in strength])
                self.stratum = " ".join([f"{int(s)}" for s in stratum])
                return
            else:
                # Assume the user has given a valid string, e.g. "i1 i2 i3"
                # Convert to the input expected by this class,
                segment = [int(s) for s in segment.split(" ")]
            
        # If segment is not a string nor a list, likely it's an int.
        if not isinstance(segment, list):
            # assume a single int is given,
            segment = [segment]
        N = len(segment)    
        # Final formatting,
        if len(strength) != N:
            # Distribute the strength,
            strength = [float(strength[0])/N]*N
        if len(stratum) != N:
            stratum = [stratum[0]]*N

        self.segment = " ".join([f"{int(s)}" for s in segment])
        self.strength = " ".join([f"{s:.3e}" for s in strength])
        self.stratum = " ".join([f"{int(s)}" for s in stratum])

        return

    def check_segments(self, max_line_len=275):
        """ Method to check the segment/strength/stratum data and reformat if needed into a sourcefile.
        Lines in the 'db.in' file (below) can only be LINELEN(=300 for this build), if they're too long the
        Source must be specified via a sourcefile.txt instead of directly in db.in.
        """
        line_lens = [len(self.segment), len(self.strength), len(self.stratum)]
        if any([l >= max_line_len for l in line_lens]):
            print("WARNING: Some lines in 'db.in' may exceed the maximum line length! - writing equivalent 'sourcefile.txt'")
            # Convert the segment, strength, and stratum back into lists...
            strength = [float(s) for s in self.strength.split(" ")]
            stratum = [int(s) for s in self.stratum.split(" ")]
            segment = [int(s) for s in self.segment.split(" ")]
            write_sourcefile_from_segments(strength=strength, stratum=stratum, segment=segment, filename="sourcefile.txt")
            self.sourcefile = "sourcefile.txt" # This will use the sourcefile instead of the strength/stratum/segment attrs. 
            self.sourcefile_fmt = "tabular" 
            
        return

def write_sourcefile_from_segments(strength=[1e24], stratum=[3], segment=[1], filename="sourcefile.txt"):
    """ Function to write a sourcefile.txt in TABULAR format defining more distributed sources.
    Kwargs:
        strength:
        stratum:
        segment:
        filename:
    """
    f = open(filename, "w")
    f.write("# Sourcefile automatically generated by script\n")
    f.write("# i_stratum i_segment S_strength\n")
    for strat, seg, S in zip(stratum, segment, strength):
        f.write(f"{int(strat)} {int(seg)} {S}\n")
    f.close()
    

def write_db_input(source_groups,plasmafile="plasmafile.txt",filename="db.in"):
    """ Function to write the 'db.in' input file for the defineback program.
    String formatting is important here because these values will be read by FORTRAN
    Args:
        source_groups: (Source type) object with necessary data as attrs.
        plasmafile: (str) filename containing the plasma background.
        filename: (str) filename written by this function.

    WARNING: in defineback.web, lines from this file are read into the variable 'line'
        declared with,
            >> character*LINELEN, line (e.g. ln 1088 in defineback.web)
        Thus, there is an implicit maximum line length limiting the number of sources.
        This common variable "LINELEN" appears to be set to 300 in 'macros.hweb'.
    """
    Nsource=len(source_groups)
    f = open(filename,"w") 
    f.write(f"plasma_file {plasmafile}\n")
    # For each source group, 
    for i in range(0,Nsource):
        source = source_groups[i]
        f.write("new_source_group\n")
        f.write(f"  source_type {source.type}\n")
        f.write("  source_geom surface\n")
        f.write(f"  source_species {source.species}\n")
        f.write(f"  source_root_sp {source.rootspecies}\n")
        f.write(f"  {source.specify_units}\n")
        if source.sourcefile is not None:
            f.write(f"  source_file {source.sourcefile} {source.sourcefile_fmt}\n")
        else:
            f.write(f"  source_stratum {source.stratum}\n")
            f.write(f"  source_segment {source.segment}\n")
            f.write(f"  source_strength {source.strength}\n")
        if source.pufftemp:
            f.write(f"  source_puff_temp {source.pufftemp}\n")
        f.write(f"  source_nflights {int(source.nflights)}\n")
        f.write("end_source_group\n")
    f.close()


