bin_PROGRAMS = randomtest datasetup
randomtest_SOURCES = sysdep.f string.f 
datasetup_SOURCES = sysdep.f string.f 
#datasetup_SOURCES = datasetup.f elementread.f speciesetup.f pmisetup.f reactionsetup.f elementsetup.f sources.f string.f geometry.f materialsetup.f randother.f random.f readfilenames.f netcdf.hweb sysdep.f interpolate.f zone_mod.f species_mod.f sources_mod.f sector_mod.f readfilenames_mod.f reaction_mod.f pmi_mod.f problem_mod.f background_mod.f geomint_mod.f materials_mod.f element_mod.f detector_mod.f
include Makefile.depends

#randomtest_deps = randomtest.f random.f
#datasetup_deps = datasetup.f elementread.f pmimatread.f elementsetup.f speciesetup.f reactionsetup.f materialsetup.f pmisetup.f readfilenames.f
randomtest_SOURCES += randomtest.f random.f
datasetup_SOURCES += datasetup.f elementread.f pmimatread.f elementsetup.f speciesetup.f reactionsetup.f materialsetup.f pmisetup.f readfilenames.f
#datasetup_deps = $(datasetup_mods) $(elementread_mods) $(pmimatread_mods) $(elementsetup_mods) $(speciesetup_mods) $(reactionsetup_mods) $(materialsetup_mods) $(pmisetup_mods) $(readfilenames_mod)
datasetup_SOURCES += $(datasetup_moddeps)

elmod=element_mod.f
znmod=zone_mod.f

#datasetup_SOURCES += background_mod.f element_mod.f reaction_mod.f readfilenames_mod.f sources_mod.f species_mod.f $(znmod) materials_mod.f output_mod.f pmidata_mod.f problem_mod.f  reactiondata_mod.f tally_mod.f pmi_mod.f


LDADD=${LIBNETCDF_LIBS}

#### DO NOT DELETE THIS LINE. *_SOURCES below automatically generated by make depend
#### DO NOT DELETE THIS LINE.

SUFFIXES = .web .hweb .mweb _mod.f

AM_FFLAGS=-fallow-argument-mismatch $(LDFLAGS)
AM_FFLAGS+=-ffixed-form

#FTANGLE=$(PWD)/../fweb/Web/ftangle
FTANGLE=ftangle
TANGLEFLAGS=-mINLINE -W[ -n/ -n')' -Tv -j -yn8000 -yb200000 -ybs15000 -mFORTRAN90 -mMACOSX -mGFORTRAN


#FC=gfortran
#AM_FFLAGS+=-fPIC -g
#LD=$(FC)

.PRECIOUS: %.f %.web.f

.web.f: 
	$(FTANGLE) $(TANGLEFLAGS) $<

#%.mweb: %.hweb makemodule
.hweb.mweb: makemodule
	./makemodule $< $@

makemodule: makemodule.sh
	cp $< $@
	chmod a+x $@

#%_mod.f: %.mweb array.hweb sysdep.hweb
.mweb_mod.f: array.hweb sysdep.hweb
	$(FTANGLE) $(TANGLEFLAGS) -=n=#_mod.f $<

makedepend: makedepend.sh
	cp $< $@
	chmod a+x $@

parsedepends: parsedepends.sh
	cp $< $@
	chmod a+x $@

depend: makedepend parsedepends
	./makedepend *.web *.hweb
	./parsedepends


#FORTRAN90=yes
#O=o
#-include Makefile.depends

#randomtest_SOURCES += $(randomtest_deps) $(foreach arg,$(subst .f,_mods,$(randomtest_deps)),$($(arg)))
	
#datasetup_SOURCES += $(datasetup_deps) $(foreach arg,$(subst .f,_mods,$(datasetup_deps)),$($(arg)))
#randomtest$(EXEEXT): sysdep.o random.o string.o

#randomtest.f: array.hweb constants.hweb macros.hweb random.hweb sysdep.hweb vector.hweb sysdep.o

#.f.o:
#	$(FC) -c $(AM_FFLAGS) $<

#%: %.o
#	$(LD) $^ -o $@

